# Generated by Django 3.1.6 on 2021-03-02 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfid_A', models.CharField(max_length=200, unique=True)),
                ('rfid_B', models.CharField(max_length=200, unique=True)),
                ('weight', models.IntegerField(default=-1)),
                ('nickname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PresenceFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=200)),
                ('comments', models.CharField(max_length=200)),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='date uploaded')),
                ('processing_status', models.BooleanField()),
                ('upload', models.FileField(upload_to='uploads/presence/')),
            ],
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.BooleanField()),
                ('reader', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('pig_rfid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.pig')),
            ],
        ),
    ]
