# Generated by Django 3.1.6 on 2021-02-25 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pig',
            fields=[
                ('rfid', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='presencefile',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date uploaded'),
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.BooleanField()),
                ('reader', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('pig_rfid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.pig')),
            ],
        ),
    ]
