# Generated by Django 3.1.6 on 2021-04-20 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_add_file_fk_to_presence_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=200, unique=True)),
                ('comments', models.CharField(max_length=200)),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='date uploaded')),
                ('processing_status', models.BooleanField()),
                ('upload', models.FileField(upload_to='uploads/weather/')),
            ],
        ),
        migrations.AlterField(
            model_name='presencefile',
            name='file_name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('pressure', models.FloatField()),
                ('humidity', models.FloatField()),
                ('timestamp', models.DateTimeField()),
                ('weather_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.weatherfile')),
            ],
        ),
    ]
